apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: websql
spec:
  storageClassName: nfspool
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - soft
  nfs:
    path: /storage/databases
    server: desktop.training.local
    readOnly: false
