apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrock
  labels:
    app: websql
  annotations:
    maintainer: "Guru the Great"
    state: "In progress"
spec:
  replicas: {{ .Values.webservice.replicacount }}
  selector:
    matchLabels:
      pod: websql-web
  template:
    metadata:
      labels:
        pod: websql-web
        app: websql
    spec:
      containers:
      - name: webcont
        image: atcomp/apacherock
        ports:
        - containerPort: 80
        env:
        - name: DBSERVER
          value: mysqlserver
        - name: DBNAME
          value: rockdisc
        - name: DBUSER
          value: guru00
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: gurupw
              key: password
        volumeMounts:
        - name: timezonehost
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: timezonehost
        hostPath:
          path: /etc/localtime
